# -*- coding: utf-8 -*-
"""NBAEstatisticas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K7cFas9LKOnkQjPzlq-MsCzYWMydXb6F
"""

!pip install nba_api plotly ipywidgets

from nba_api.stats.endpoints import leaguedashplayerstats
import pandas as pd
import plotly.express as px
import ipywidgets as widgets
from IPython.display import display

print("🔄 Carregando dados da NBA...")

stats = leaguedashplayerstats.LeagueDashPlayerStats(
    season='2025-26',
    season_type_all_star='Regular Season'
)

df = stats.get_data_frames()[0]

# ==============================
# 🧠 TRATAMENTO PROFISSIONAL
# ==============================

# Totais reais (corrigido)
df['PTS_TOTAL'] = df['PTS'] * df['GP']
df['REB_TOTAL'] = df['REB'] * df['GP']
df['AST_TOTAL'] = df['AST'] * df['GP']

# Média de minutos
df['MIN_AVG'] = df['MIN'] / df['GP']

# TS% (True Shooting)
df['TS%'] = df['PTS'] / (2 * (df['FGA'] + 0.44 * df['FTA']))

print("✅ Dados prontos!")

# ==============================
# 🔎 INTERFACE
# ==============================

search = widgets.Text(
    placeholder='Digite nome do jogador',
    description='Buscar:'
)

dropdown1 = widgets.Dropdown(description='Jogador 1:')
dropdown2 = widgets.Dropdown(description='Jogador 2:')

output = widgets.Output()

# Atualizar lista
def update_list(change):
    nome = search.value.lower()
    filtered = df[df['PLAYER_NAME'].str.lower().str.contains(nome)]

    lista = sorted(filtered['PLAYER_NAME'].unique())

    if lista:
        dropdown1.options = lista
        dropdown2.options = lista

search.observe(update_list, names='value')

# ==============================
# 📊 FUNÇÃO PRINCIPAL
# ==============================

def show_dashboard(change):
    with output:
        output.clear_output()

        p1 = df[df['PLAYER_NAME'] == dropdown1.value].iloc[0]
        p2 = df[df['PLAYER_NAME'] == dropdown2.value].iloc[0]

        print(f"\n🏀 COMPARAÇÃO: {p1['PLAYER_NAME']} vs {p2['PLAYER_NAME']}")

        # ==============================
        # 📊 TABELA COMPARATIVA
        # ==============================

        comp = pd.DataFrame({
            'Stat': ['PTS', 'REB', 'AST', 'MIN', 'TS%'],
            p1['PLAYER_NAME']: [
                p1['PTS'], p1['REB'], p1['AST'], p1['MIN_AVG'], p1['TS%']
            ],
            p2['PLAYER_NAME']: [
                p2['PTS'], p2['REB'], p2['AST'], p2['MIN_AVG'], p2['TS%']
            ]
        })

        display(comp)

        # ==============================
        # 📈 RADAR COMPARATIVO
        # ==============================

        radar_df = pd.DataFrame({
            'Categoria': ['PTS', 'REB', 'AST', 'STL', 'BLK'],
            p1['PLAYER_NAME']: [p1['PTS'], p1['REB'], p1['AST'], p1['STL'], p1['BLK']],
            p2['PLAYER_NAME']: [p2['PTS'], p2['REB'], p2['AST'], p2['STL'], p2['BLK']]
        })

        fig = px.line_polar(
            radar_df.melt(id_vars='Categoria'),
            r='value',
            theta='Categoria',
            color='variable',
            line_close=True
        )

        fig.show()

        # ==============================
        # 📊 BARRAS COMPARATIVAS
        # ==============================

        fig2 = px.bar(
            radar_df.melt(id_vars='Categoria'),
            x='Categoria',
            y='value',
            color='variable',
            barmode='group'
        )

        fig2.show()

        # ==============================
        # 🏆 TOP 10 DA LIGA
        # ==============================

        top10 = df.sort_values(by='PTS', ascending=False).head(10)

        fig3 = px.bar(
            top10,
            x='PLAYER_NAME',
            y='PTS',
            title='Top 10 Pontuadores'
        )

        fig3.show()

dropdown1.observe(show_dashboard, names='value')
dropdown2.observe(show_dashboard, names='value')

display(search, dropdown1, dropdown2, output)